version: '3.4'

services:

  # App Service
  app:
    # Configuration for building the docker image for the service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: on-failure
    env_file:
      - .env
    depends_on: 
      - fullstack-postgres # This service depends on redis. Start that first.
    # links:
    #  - postgres
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - mynetwork
     
  fullstack-postgres:
    container_name: full_db_postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: "FindGamingFriends"
      PGDATA: /data/postgres
    volumes:
      - database-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always
    networks:
       - mynetwork
    
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
     PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: always
    depends_on:
      - fullstack-postgres 
    networks:
      - mynetwork
    volumes:
      - pgadmin:/root/.pgadmin

volumes:
  database-data:
  pgadmin:

networks:
 mynetwork:
  driver: bridge